language: cpp
addons:
  apt:
    packages:
      - ninja-build
      - libasio-dev
      - googletest
before_script:
  - cd /usr/src/googletest
  - mkdir build && cd build
  - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --target install
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - cd $TRAVIS_BUILD_DIR
script:
  - mkdir build && cd build
  - cmake -GNinja ..
  - ninja
  - ctest