language: cpp
addons:
  apt:
    packages:
      - ninja-build
      - libasio-dev
      - libgtest-dev
      - cmake
before_script:
  - sudo apt-get intall googletest -y
  - cd /usr/src/gtest
  - sudo mkdir build && cd build
  - sudo cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
  - sudo cmake --install . --verbose
  - cd $TRAVIS_BUILD_DIR
script:
  - mkdir build && cd build
  - cmake -GNinja ..
  - ninja
  - ctest