language: cpp
addons:
  apt:
    packages:
      - ninja-build
      - libasio-dev
      - libgtest-dev
      - cmake
before_script:
  - cd /usr/src/gtest
  - sudo mkdir build && cd build
  - sudo cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DINSTALL_GTEST=ON
  - sudo cmake --install .
  - cd $TRAVIS_BUILD_DIR
script:
  - mkdir build && cd build
  - cmake -GNinja ..
  - ninja
  - ctest