language: cpp
addons:
  apt:
    packages:
      - doxygen
      - cmake
      - googletest
      - ninja-build
before_script:
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - cd $TRAVIS_BUILD_DIR
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test