language: cpp
addons:
  apt:
    packages:
      - ninja-build
      - libasio-dev
      - libgtest-dev
before_script:
  - cd /usr/src/gtest
  - sudo mkdir build && cd build
  - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --target install
  - cd $TRAVIS_BUILD_DIR
script:
  - mkdir build && cd build
  - cmake -GNinja ..
  - ninja
  - ctest